using System.Collections.Generic;

namespace TPRandomizer
{
    public class Checks
    {
        public static List<string> RandomizerChecks = new List<string>()
        {
            "Forest Temple Entrance Vines Chest",
            "Forest Temple Central Chest Behind Stairs",
            "Forest Temple Central North Chest",
            "Forest Temple Windless Bridge Chest",
            "Forest Temple Second Monkey Under Bridge Chest",
            "Forest Temple Totem Pole Chest",
            "Forest Temple West Tile Worm Room Vines Chest",
            "Forest Temple West Deku Like Chest",
            "Forest Temple West Tile Worm Chest Behind Stairs",
            "Forest Temple Gale Boomerang",
            "Forest Temple Central Chest Hanging From Web",
            "Forest Temple Big Key Chest",
            "Forest Temple East Water Cave Chest",
            "Forest Temple North Deku Like Chest",
            "Forest Temple East Tile Worm Chest",
            "Forest Temple Diababa Heart Container",
            "Goron Mines Entrance Chest",
            "Goron Mines Main Magnet Room Bottom Chest",
            "Goron Mines Gor Amato Chest",
            "Goron Mines Gor Amato Key Shard",
            "Goron Mines Gor Amato Small Chest",
            "Goron Mines Magnet Maze Chest",
            "Goron Mines Crystal Switch Room Underwater Chest",
            "Goron Mines Crystal Switch Room Small Chest",
            "Goron Mines After Crystal Switch Room Magnet Wall Chest",
            "Goron Mines Outside Beamos Chest",
            "Goron Mines Gor Ebizo Chest",
            "Goron Mines Gor Ebizo Key Shard",
            "Goron Mines Chest Before Dangoro",
            "Goron Mines Dangoro Chest",
            "Goron Mines Beamos Room Chest",
            "Goron Mines Gor Liggs Chest",
            "Goron Mines Gor Liggs Key Shard",
            "Goron Mines Main Magnet Room Top Chest",
            "Goron Mines Outside Underwater Chest",
            "Goron Mines Fyrus Heart Container",
            "Lakebed Temple Lobby Left Chest",
            "Lakebed Temple Lobby Rear Chest",
            "Lakebed Temple Stalactite Room Chest",
            "Lakebed Temple Central Room Small Chest",
            "Lakebed Temple Central Room Chest",
            "Lakebed Temple East Lower Waterwheel Stalactite Chest",
            "Lakebed Temple East Second Floor Southwest Chest",
            "Lakebed Temple East Second Floor Southeast Chest",
            "Lakebed Temple East Water Supply Small Chest",
            "Lakebed Temple Before Deku Toad Alcove Chest",
            "Lakebed Temple Before Deku Toad Underwater Left Chest",
            "Lakebed Temple Before Deku Toad Underwater Right Chest",
            "Lakebed Temple Deku Toad Chest",
            "Lakebed Temple Chandelier Chest",
            "Lakebed Temple East Water Supply Clawshot Chest",
            "Lakebed Temple Central Room Spire Chest",
            "Lakebed Temple West Lower Small Chest",
            "Lakebed Temple West Water Supply Small Chest",
            "Lakebed Temple West Water Supply Chest",
            "Lakebed Temple West Second Floor Southwest Underwater Chest",
            "Lakebed Temple West Second Floor Central Small Chest",
            "Lakebed Temple West Second Floor Northeast Chest",
            "Lakebed Temple West Second Floor Southeast Chest",
            "Lakebed Temple Big Key Chest",
            "Lakebed Temple Underwater Maze Small Chest",
            "Lakebed Temple East Lower Waterwheel Bridge Chest",
            "Lakebed Temple Morpheel Heart Container",
            "Arbiters Grounds Lobby Chest",
            "Arbiters Grounds East Lower Turnable Redead Chest",
            "Arbiters Grounds Torch Room East Chest",
            "Arbiters Grounds Torch Room West Chest",
            "Arbiters Grounds East Upper Turnable Chest",
            "Arbiters Grounds East Upper Turnable Redead Chest",
            "Arbiters Grounds Ghoul Rat Room Chest",
            "Arbiters Grounds West Small Chest Behind Block",
            "Arbiters Grounds West Chandelier Chest",
            "Arbiters Grounds West Stalfos North Chest",
            "Arbiters Grounds West Stalfos Southeast Chest",
            "Arbiters Grounds North Turning Room Chest",
            "Arbiters Grounds Death Sword Chest",
            "Arbiters Grounds Spinner Room First Small Chest",
            "Arbiters Grounds Spinner Room Second Small Chest",
            "Arbiters Grounds Spinner Room Lower Central Small Chest",
            "Arbiters Grounds Spinner Room Stalfos Alcove Chest",
            "Arbiters Grounds Spinner Room Lower North Chest",
            "Arbiters Grounds Big Key Chest",
            "Arbiters Grounds Stallord Heart Container",
            "Snowpeak Ruins West Courtyard Buried Chest",
            "Snowpeak Ruins East Courtyard Buried Chest",
            "Snowpeak Ruins Ordon Pumpkin Chest",
            "Snowpeak Ruins East Courtyard Chest",
            "Snowpeak Ruins Wooden Beam Central Chest",
            "Snowpeak Ruins Wooden Beam Northwest Chest",
            "Snowpeak Ruins Courtyard Central Chest",
            "Snowpeak Ruins Ball and Chain",
            "Snowpeak Ruins Chest After Darkhammer",
            "Snowpeak Ruins Broken Floor Chest",
            "Snowpeak Ruins Wooden Beam Chandelier Chest",
            "Snowpeak Ruins Lobby Chandelier Chest",
            "Snowpeak Ruins Lobby West Armor Chest",
            "Snowpeak Ruins Lobby East Armor Chest",
            "Snowpeak Ruins Northeast Chandelier Chest",
            "Snowpeak Ruins West Cannon Room Central Chest",
            "Snowpeak Ruins West Cannon Room Corner Chest",
            "Snowpeak Ruins Chapel Chest",
            "Snowpeak Ruins Blizzeta Heart Container",
            "Temple of Time Lobby Lantern Chest",
            "Temple of Time First Staircase Gohma Gate Chest",
            "Temple of Time First Staircase Window Chest",
            "Temple of Time First Staircase Armos Chest",
            "Temple of Time Statue Throws Room East Chest",
            "Temple of Time Moving Wall Beamos Room Chest",
            "Temple of Time Scales Gohma Chest",
            "Temple of Time Gilloutine Chest",
            "Temple of Time Chest Before Darknut",
            "Temple of Time Darknut Chest",
            "Temple of Time Scales Upper Chest",
            "Temple of Time Big Key Chest Room Upper Chest",
            "Temple of Time Big Key Chest",
            "Temple of Time Moving Wall Dinalfos Room Chest",
            "Temple of Time Statue Throws Room North Chest",
            "Temple of Time Statue Throws Room Statue Chest",
            "Temple of Time Armogohma Heart Container",
            "City in The Sky Underwater West Chest",
            "City in The Sky Underwater East Chest",
            "City in The Sky West Wing First Chest",
            "City in The Sky East First Wing Chest After Fans",
            "City in The Sky East Tile Worm Small Chest",
            "City in The Sky East Wing After Dinalfos Alcove Chest",
            "City in The Sky East Wing After Dinalfos Ledge Chest",
            "City in The Sky Aeralfos Chest",
            "City in The Sky East Wing Lower Level Chest",
            "City in The Sky West Wing Baba Balcony Chest",
            "City in The Sky West Wing Narrow Ledge Chest",
            "City in The Sky West Wing Tile Worm Chest",
            "City in The Sky Baba Tower Top Small Chest",
            "City in The Sky Baba Tower Narrow Ledge Chest",
            "City in The Sky Baba Tower Alcove Chest",
            "City in The Sky West Garden Corner Chest",
            "City in The Sky West Garden Lone Island Chest",
            "City in The Sky West Garden Lower Chest",
            "City in The Sky West Garden Ledge Chest",
            "City in The Sky Central Outside Ledge Chest",
            "City in The Sky Central Outside Poe Island Chest",
            "City in The Sky Big Key Chest",
            "City in The Sky Chest Below Big Key Chest",
            "City in The Sky Chest Behind North Fan",
            "City in The Sky Argorok Heart Container",
            "Palace of Twilight West Wing First Room Central Chest",
            "Palace of Twilight West Wing Second Room Central Chest",
            "Palace of Twilight West Wing Second Room Lower South Chest",
            "Palace of Twilight West Wing Second Room Southeast Chest",
            "Palace of Twilight West Wing Chest Behind Wall of Darkness",
            "Palace of Twilight East Wing First Room North Small Chest",
            "Palace of Twilight East Wing First Room Zant Head Chest",
            "Palace of Twilight East Wing Second Room Northeast Chest",
            "Palace of Twilight East Wing Second Room Northwest Chest",
            "Palace of Twilight East Wing Second Room Southwest Chest",
            "Palace of Twilight East Wing Second Room Southeast Chest",
            "Palace of Twilight East Wing First Room East Alcove",
            "Palace of Twilight East Wing First Room West Alcove",
            "Palace of Twilight Collect Both Sols",
            "Palace of Twilight Central First Room Chest",
            "Palace of Twilight Big Key Chest",
            "Palace of Twilight Central Outdoor Chest",
            "Palace of Twilight Central Tower Chest",
            "Palace of Twilight Zant Heart Container",
            "Hyrule Castle Graveyard Grave Switch Room Right Chest",
            "Hyrule Castle Graveyard Grave Switch Room Front Left Chest",
            "Hyrule Castle Graveyard Grave Switch Room Back Left Chest",
            "Hyrule Castle Graveyard Owl Statue Chest",
            "Hyrule Castle East Wing Boomerang Puzzle Chest",
            "Hyrule Castle East Wing Balcony Chest",
            "Hyrule Castle West Courtyard North Small Chest",
            "Hyrule Castle West Courtyard Central Small Chest",
            "Hyrule Castle Main Hall Northeast Chest",
            "Hyrule Castle Lantern Staircase Chest",
            "Hyrule Castle Main Hall Southwest Chest",
            "Hyrule Castle Main Hall Northwest Chest",
            "Hyrule Castle Southeast Balcony Tower Chest",
            "Hyrule Castle Big Key Chest",
            "Hyrule Castle Treasure Room Eighth Small Chest",
            "Hyrule Castle Treasure Room Seventh Small Chest",
            "Hyrule Castle Treasure Room Sixth Small Chest",
            "Hyrule Castle Treasure Room Fifth Small Chest",
            "Hyrule Castle Treasure Room Fourth Small Chest",
            "Hyrule Castle Treasure Room Third Small Chest",
            "Hyrule Castle Treasure Room Second Small Chest",
            "Hyrule Castle Treasure Room First Small Chest",
            "Hyrule Castle Treasure Room Fifth Chest",
            "Hyrule Castle Treasure Room Fourth Chest",
            "Hyrule Castle Treasure Room Third Chest",
            "Hyrule Castle Treasure Room Second Chest",
            "Hyrule Castle Treasure Room First Chest",
            "Uli Cradle Delivery",
            "Ordon Cat Rescue",
            "Sera Shop Slingshot",
            "Gift From Rusl",
            "Coro Lantern",
            "South Faron Cave Chest",
            "Faron Mist Cave Open Chest",
            "Faron Mist Cave Lantern Chest",
            "North Faron Woods Deku Baba Chest",
            "Links Basement Chest",
            "Ordon Shield",
            "Ordon Sword",
            "Herding Goats Reward",
            "Kakariko Village Bomb Rock Spire Heart Piece",
            "Faron Field Tree Heart Piece",
            "Kakariko Gorge Spire Heart Piece",
            "Kakariko Inn Chest",
            "Wrestling With Bo",
            "Barnes Bomb Bag",
            "Eldin Spring Underwater Chest",
            "Kakariko Graveyard Lantern Chest",
            "Kakariko Watchtower Chest",
            "Kakariko Watchtower Alcove Chest",
            "Eldin Field Bomb Rock Chest",
            "Zoras Domain Chest By Mother and Child Isles",
            "Zoras Domain Chest Behind Waterfall",
            "Lake Hylia Underwater Chest",
            "Fishing Hole Heart Piece",
            "Sacred Grove Baba Serpent Grotto Chest",
            "West Hyrule Field Helmasaur Grotto Chest",
            "STAR Prize 1",
            "STAR Prize 2",
            "Lake Lantern Cave First Chest",
            "Lake Lantern Cave Second Chest",
            "Lake Lantern Cave Third Chest",
            "Lake Lantern Cave Fourth Chest",
            "Lake Lantern Cave Fifth Chest",
            "Lake Lantern Cave Sixth Chest",
            "Lake Lantern Cave Seventh Chest",
            "Lake Lantern Cave Eighth Chest",
            "Lake Lantern Cave Ninth Chest",
            "Lake Lantern Cave Tenth Chest",
            "Lake Lantern Cave Eleventh Chest",
            "Lake Lantern Cave Twelfth Chest",
            "Lake Lantern Cave Thirteenth Chest",
            "Lake Lantern Cave Fourteenth Chest",
            "Lake Lantern Cave End Lantern Chest",
            "Lake Hylia Water Toadpoli Grotto Chest",
            "Outside Lanayru Spring Left Statue Chest",
            "Outside Lanayru Spring Right Statue Chest",
            "Lanayru Spring Underwater Left Chest",
            "Lanayru Spring Underwater Right Chest",
            "Lanayru Spring Back Room Left Chest",
            "Lanayru Spring Back Room Right Chest",
            "Lanayru Spring Back Room Lantern Chest",
            "Flight By Fowl Top Platform Chest",
            "Flight By Fowl Second Platform Chest",
            "Flight By Fowl Third Platform Chest",
            "Flight By Fowl Fourth Platform Chest",
            "Flight By Fowl Fifth Platform Chest",
            "Lake Hylia Shell Blade Grotto Chest",
            "Agitha First Bug Pair Reward",
            "Agitha Second Bug Pair Reward",
            "Agitha Third Bug Pair Reward",
            "Agitha Fourth Bug Pair Reward",
            "Agitha Fifth Bug Pair Reward",
            "Agitha Sixth Bug Pair Reward",
            "Agitha Seventh Bug Pair Reward",
            "Agitha Eighth Bug Pair Reward",
            "Agitha Ninth Bug Pair Reward",
            "Agitha Tenth Bug Pair Reward",
            "Agitha Eleventh Bug Pair Reward",
            "Agitha Final Bug Pair Reward",
            "Agitha First Single Bug Reward",
            "Agitha Second Single Bug Reward",
            "Agitha Third Single Bug Reward",
            "Agitha Fourth Single Bug Reward",
            "Agitha Fifth Single Bug Reward",
            "Agitha Sixth Single Bug Reward",
            "Agitha Seventh Single Bug Reward",
            "Agitha Eighth Single Bug Reward",
            "Agitha Ninth Single Bug Reward",
            "Agitha Tenth Single Bug Reward",
            "Agitha Eleventh Single Bug Reward",
            "Agitha Twelfth Single Bug Reward",
            "Zoras Domain Light All Torches Chest",
            "Zoras Domain Extinguish All Torches Chest",
            "Lanayru Field Skulltula Grotto Chest",
            "Lanayru Field Behind Gate Underwater Chest",
            "Lake Hylia Bridge Vines Chest",
            "Lake Hylia Bridge Bubble Grotto Chest",
            "Lake Hylia Bridge Cliff Chest",
            "Faron Field Bridge Chest",
            "Faron Field Corner Grotto Right Chest",
            "Faron Field Corner Grotto Rear Chest",
            "Faron Field Corner Grotto Left Chest",
            "Death Mountain Alcove Chest",
            "Goron Mines Outside Clawshot Chest",
            "Eldin Lantern Cave First Chest",
            "Eldin Lantern Cave Lantern Chest",
            "Eldin Lantern Cave Second Chest",
            "Outside South Castle Town Tightrope Chest",
            "Outside South Castle Town Tetike Grotto Chest",
            "Eldin Field Bomskit Grotto Left Chest",
            "Eldin Field Bomskit Grotto Lantern Chest",
            "Eldin Field Water Bomb Fish Grotto Chest",
            "Gerudo Desert Skulltula Grotto Chest",
            "Gerudo Desert Peahat Ledge Chest",
            "Gerudo Desert East Canyon Chest",
            "Gerudo Desert Lone Small Chest",
            "Eldin Stockcave Upper Chest",
            "Eldin Stockcave Lantern Chest",
            "Eldin Stockcave Lowest Chest",
            "Gerudo Desert West Canyon Chest",
            "Gerudo Desert Poe Grotto Lantern Chest",
            "Gerudo Desert Northeast Chest Behind Gates",
            "Gerudo Desert South Chest Behind Wooden Gates",
            "Gerudo Desert Campfire North Chest",
            "Gerudo Desert Campfire East Chest",
            "Gerudo Desert Campfire West Chest",
            "Gerudo Desert Northwest Chest Behind Gates",
            "Gerudo Desert North Small Chest Before Bulblin Camp",
            "Bulblin Camp First Chest Under Tower At Entrance",
            "Bulblin Camp Small Chest in Back of Camp",
            "Outside Arbiters Grounds Lantern Chest",
            "Lanayru Field Spinner Track Chest",
            "Lanayru Field Stalfos Grotto Right Small Chest",
            "Lanayru Field Stalfos Grotto Left Small Chest",
            "Lanayru Field Stalfos Grotto Stalfos Chest",
            "Outside South Castle Town Fountain Chest",
            "Ordon Ranch Grotto Lantern Chest",
            "Faron Mist Stump Chest",
            "Faron Mist North Chest",
            "Faron Mist South Chest",
            "Snowpeak Cave Ice Lantern Chest",
            "Snowpeak Freezard Grotto Chest",
            "Lanayru Ice Block Puzzle Cave Chest",
            "Lost Woods Lantern Chest",
            "Sacred Grove Spinner Chest",
            "Sacred Grove Past Owl Statue Chest",
            "Doctors Office Balcony Chest",
            "Bridge of Eldin Owl Statue Chest",
            "Kakariko Gorge Owl Statue Chest",
            "Hyrule Field Ampitheater Owl Statue Chest",
            "Lake Hylia Bridge Owl Statue Chest",
            "Faron Woods Owl Statue Chest",
            "Gerudo Desert Owl Statue Chest",
            "Faron Woods Owl Statue Sky Character",
            "Kakariko Gorge Owl Statue Sky Character",
            "Bridge of Eldin Owl Statue Sky Character",
            "Lake Hylia Bridge Owl Statue Sky Character",
            "Hyrule Field Ampitheater Owl Statue Sky Character",
            "Gerudo Desert Owl Statue Sky Character",
            "Kakariko Gorge Double Clawshot Chest",
            "Lanayru Spring East Double Clawshot Chest",
            "Lanayru Spring West Double Clawshot Chest",
            "Outside South Castle Town Double Clawshot Chasm Chest",
            "Cats Hide and Seek Minigame",
            "Iza Raging Rapids Minigame",
            "Auru Gift To Fyer",
            "Ashei Sketch",
            "Renardos Letter",
            "Telma Invoice",
            "Wooden Statue",
            "Ilia Charm",
            "Ilia Memory Reward",
            "Coro Bottle",
            "Fishing Hole Bottle",
            "Talo Sharpshooting",
            "Charlo Donation Blessing",
            "Goron Springwater Rush",
            "Plumm Fruit Balloon Minigame",
            "Bulblin Camp Roasted Boar",
            "Snowpeak Ruins Mansion Map",
            "Snowboard Racing Prize",
            "Hyrule Castle King Bulblin Key",
            "Forest Temple Big Baba Key",
            "Iza Helping Hand",
            "Zoras Domain Underwater Goron",
            "Gift From Ralis",
            "Rutelas Blessing",
            "Ganondorf Defeated",
        };
    }
}